/* Generated by script/generate-design-tokens.ts. Do not edit by hand. */

export const TOKENS = {
  animation: {
    durationMs: {
      fast: 150,
      default: 200,
      slow: 300,
    },
    easing: {
      defaultCss: "cubic-bezier(0.4, 0, 0.2, 1)",
      defaultBezier: [0.4,0,0.2,1],
    },
  },
  touchTargets: {
    minimum: "44px",
    comfortable: "48px",
  },
} as const;

export type Tokens = typeof TOKENS;
