/* Generated by script/generate-design-tokens.ts. Do not edit by hand. */

export const TOKENS = {
  animation: {
    durationMs: {
      fast: 200,
      default: 250,
      slow: 300,
    },
    easing: {
      defaultCss: "cubic-bezier(0.4, 0, 0.2, 1)",
      defaultBezier: [0.4,0,0.2,1],
    },
  },
  shadows: {
    soft: "0 1px 3px rgba(28, 42, 56, 0.06)",
    card: "0 2px 8px rgba(28, 42, 56, 0.08)",
    elevated: "0 4px 16px rgba(28, 42, 56, 0.12)",
  },
  touchTargets: {
    minimum: "44px",
    comfortable: "48px",
  },
} as const;

export type Tokens = typeof TOKENS;
